// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace T4
{

    // UserInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class UserInfoEntityMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserInfoEntity>
    {
        public UserInfoEntityMap()
            : this("dbo")
        {
        }

        public UserInfoEntityMap(string schema)
        {
            ToTable("UserInfo", schema);
            HasKey(x => x.F_Id);

            Property(x => x.F_Id).HasColumnName(@"F_Id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.F_Name).HasColumnName(@"F_Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.F_PassWord).HasColumnName(@"F_PassWord").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.emailaddress).HasColumnName(@"emailaddress").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
        }
    }

}
// </auto-generated>
