// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MongoDbDemo
{

    // UserInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class UserInfoEntity
    {

        ///<summary>
        /// 姓名
        ///</summary>
        public System.Guid F_Id { get; set; } // F_Id (Primary key)
        public string F_Name { get; set; } // F_Name (length: 50)
        public string F_PassWord { get; set; } // F_PassWord (length: 50)
        public string emailaddress { get; set; } // emailaddress (length: 50)
    }

}
// </auto-generated>
